export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";
export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";

export const USER_PROFILE_UPDATE_ERROR = "USER_PROFILE_UPDATE_ERROR";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";

export const USER_CHANGE_PASSWORD_ERROR = "USER_CHANGE_PASSWORD_ERROR";
export const USER_CHANGE_PASSWORD_SUCCESS = "USER_CHANGE_PASSWORD_SUCCESS";
export const USER_CHANGE_PASSWORD_REQUEST = "USER_CHANGE_PASSWORD_REQUEST";

export const USER_TASK_ERROR = "USER_TASK_ERROR";
export const USER_TASK_SUCCESS = "USER_TASK_SUCCESS";
export const USER_TASK_REQUEST = "USER_TASK_REQUEST";

export const USER_LIST_ERROR = "USER_LIST_ERROR";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_REQUEST = "USER_LIST_REQUEST";

export const USER_ASSI_LIST_ERROR = "USER_ASSI_LIST_ERROR";
export const USER_ASSI_LIST_SUCCESS = "USER_ASSI_LIST_SUCCESS";
export const USER_ASSI_LIST_REQUEST = "USER_ASSI_LIST_REQUEST";

export const USER_TASK_ASSIGNMENT_ERROR = "USER_TASK_ASSIGNMENT_ERROR";
export const USER_TASK_ASSIGNMENT_SUCCESS = "USER_TASK_ASSIGNMENT_SUCCESS";
export const USER_TASK_ASSIGNMENT_REQUEST = "USER_TASK_ASSIGNMENT_REQUEST";

export const USER_TASK_ASSIGNMENT_CHECKED_ERROR =
  "USER_TASK_ASSIGNMENT_CHECKED_ERROR";
export const USER_TASK_ASSIGNMENT_CHECKED_SUCCESS =
  "USER_TASK_ASSIGNMENT_CHECKED_SUCCESS";
export const USER_TASK_ASSIGNMENT_CHECKED_REQUEST =
  "USER_TASK_ASSIGNMENT_CHECKED_REQUEST";

export const USER_CREATE_TASK_LIST_ERROR = "USER_CREATE_TASK_LIST_ERROR";
export const USER_CREATE_TASK_LIST_SUCCESS = "USER_CREATE_TASK_LIST_SUCCESS";
export const USER_CREATE_TASK_LIST_REQUEST = "USER_CREATE_TASK_LIST_REQUEST";

export const USER_TASK_DELETE_ERROR = "USER_TASK_DELETE_ERROR";
export const USER_TASK_DELETE_SUCCESS = "USER_TASK_DELETE_SUCCESS";
export const USER_TASK_DELETE_REQUEST = "USER_TASK_DELETE_REQUEST";

export const USER_TASK_VIEW_ERROR = "USER_TASK_VIEW_ERROR";
export const USER_TASK_VIEW_SUCCESS = "USER_TASK_VIEW_SUCCESS";
export const USER_TASK_VIEW_REQUEST = "USER_TASK_VIEW_REQUEST";
